version: '3'

services:
  mongo:
    image: mongo:3.2
    command: mongod --smallfiles
    ports:
      - "37017:27017"

  seed_data:
    build: .
    links:
      - mongo
    depends_on:
      - mongo
